# Window
kitty --start-as=maximized
window_padding_width 12
hide_window_decorations no
scrollback_lines 10000

# Font
font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_features JetBrainsMono-Regular +ss02 -calt
font_features JetBrainsMono-Bold +ss02 -calt
font_features JetBrainsMono-Italic +ss02 -calt
font_features JetBrainsMono-BoldItalic +ss02 -calt

font_size 15.0

modify_font cell_height 120%

# Cursor
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

#Misc
confirm_os_window_close 0
enable_audio_bell no
detect_urls yes 

# Clipboard
copy_on_select no

# Ctrl+Shift+C / Ctrl+Shift+V
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard


# Colors (Tokyo Night-storm)
background #222436
foreground #c8d3f5

color0  #1b1d2b
color1  #ff757f
color2  #c3e88d
color3  #ffc777
color4  #82aaff
color5  #c099ff
color6  #86e1fc
color7  #828bb8

color8  #444a73
color9  #ff8d94
color10 #c7fb6d
color11 #ffd8ab
color12 #9ab8ff
color13 #caabff
color14 #b2ebff
color15 #c8d3f5
